### ISSUE TITLE
Import Packages error: no such module 'SwiftWin32'

### ISSUE THREAD

**Issue by Alanko5** [pwsacademy/swift-setup#6]
I traing use swift on windows in VisualStudio Code.

I use external Package SwiftWin32, in Visual studio code not showing any error.
if click build then showing [error](error: no such module 'SwiftWin32')

Any ideas 

<img width="251" alt="Snímka obrazovky 2024-01-11 o 14 12 28" src="https://github.com/pwsacademy/swift-setup/assets/71501260/3c503e36-2d8f-4cd8-a17e-0abc7d3fbc89">

<img width="749" alt="Snímka obrazovky 2024-01-11 o 14 12 40" src="https://github.com/pwsacademy/swift-setup/assets/71501260/6ed74bfb-6ff2-4a36-a769-d47ae909baf3">

<img width="561" alt="Snímka obrazovky 2024-01-11 o 14 15 31" src="https://github.com/pwsacademy/swift-setup/assets/71501260/acfd72e8-e97f-46b9-9211-f0192f0fe974">

**Comment by svanimpe** [comment]
Hi @Alanko5 

This repo only contains instructions to set up Swift on Windows for novice programmers. For other questions or issues, you'll have more luck on the [Swift Forums](https://forums.swift.org) :)
